export const DEFAULT_COMMUNITY_PAGE = 1;
export const DEFAULT_COMMUNITY_LIST_PAGE_SIZE = 10;
export const DEFAULT_COMMUNITY_MEMBERS_PAGE_SIZE = 50;
export const DEFAULT_COMMUNITY_POSTS_PAGE_SIZE = 20;
export const DEFAULT_COMMUNITY_COMMENTS_LIMIT = 10;
